version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dadi1nho
      POSTGRES_PASSWORD: strongpass@
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: